# Site settings
title: Personal Data Science Portfolio
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alfredo Quintana
user_description: Mathematician and entry level Data Scientist. Wide domain in statistics and modeling, Machine Learning, Data Mining, Data Analysis, Big Data. Finding the link between Math and real life problems is what I do as a Mathematician, as a Data Scientist I develop smart solutions that find patterns and earn valuable knowledge from Data.
user_title: Mathematician & Entry Level Data Scientist
email: alfredo.quintana.14@gmail.com
twitter_username: alfredoq14
github_username:  Qalfredos
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
